DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    vardas VARCHAR(250) NOT NULL,
    pavarde VARCHAR(250) NOT NULL,
    telefono_numeris VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL,
    adresas VARCHAR(250) NOT NULL,
    slaptazodis VARCHAR(250) NOT NULL
);